Increment 8
Konab/devops-tpl pull request #8
Opened 2022-06-20 16:45 UTC by Konab

2022-06-22 18:37 UTC, sergeysergeevru requested changes
Привет! Конечно грамотное разложение по слоям очень нравится, достаточно хорошая структура приложения. Самая большая и по сути единственная серьезная проблема - это то, что синхронная запись в файл не работает. Если вдруг я не правильно понял логику работы, то можешь написать в личку и мы разберемся)

2022-06-22 18:37 UTC, sergeysergeevru commented on cmd/agent/main.go
> +	err := config.Init(cfg)
я считаю что лучше это не унести под капот NewConfig, чтобы оставить всю ответственость за настройку конфига там и получить уже говорый инстанс для работы.

2022-06-22 18:37 UTC, sergeysergeevru commented on cmd/server/main.go
> +	err := config.Init(cfg)
в принципе аналогично)

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/server/router_test.go
> +package server_test
нужен ли этот пустой файл?)

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/agent/app.go
> +	client := resty.New().SetBaseURL("http://" + cfg.Agent.ServerURL)
Сквозь призму реального проекта может стоит унести схему тоже в конфиг

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/agent/webapi.go
> +	}
Потенциально можно всю структуру entity.Metric передавать в аргументе, а не собирать здесь. Но каких-то критических проблем здесь не вижу. Разве что, у нас Value и Delta получаются инвариантными по отношению друг к другу.

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/agent/webapi.go
> +	}
хотя так как ты применяешь это в логике смотрится лаконично)

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/server/middleware.go
> +			errorHandler(w, err)
return забыл

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/server/router.go
> +		})
с анонимными функциями тяжело ориентироваться в коде. Например чтобы увидеть какие вообще ендпоинты есть надо проскролить несколько экранов и пока домотаешь до последнего забудешь какие были) Давай вынесем их отдельно, чтобы все наглядно было.

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/server/router.go
> +			w.Header().Set("Content-Type", "text/html")
не думаю что ты отдаешь в html, скоре всего в "text/plain")

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/server/router.go
> +				err := uc.StoreMetric(context.Background(), metric)
контекст можно вынуть из реквеста) Вообще если снобить, то context.Background() должен быть корневым контекстом, а для целей когда непонятно какой контекст использовать есть context.TODO(). Но черт меня дери context.Background() везде и все используют без зазрения совести. В общем основной посыл, что контекст из реквеста можно выдернуть)

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/app/server/router.go
> +		)
нужен ли это ендпоинт, если он неимплементирован?

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/usecase/devops.go
> +func (uc *DevOpsUseCase) Metric(ctx context.Context, metric entity.Metric) (entity.Metric, error) {
Metric) непонятно что делает метод.  Может Get/Fetch или еще что-нибудь metric назовем?) ИМХО код должен быть самодокументируемым)

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/usecase/devops.go
> +func (uc DevOpsUseCase) MetricNames(ctx context.Context) ([]string, error) {
тоже не понятно что делает метод. Я считаю что метод должен содержать глагол, чтобы было понятно +- что он делает в имплементации

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/usecase/devops.go
> +	}
лично у меня большой скепсис к Option паттерну, так как опциональные параметры сами себя не задокументируют в сигнатуре конструктора и тогда становится неочевидно от каких параметров зависит коструктор. Для каких-то огромных библиотек паттерн может и уместный, но как по мне, для небольших проектов overengineering. Но судя по тому что ты все таки выделил некоторые аргументы в обязательные, то применение вполне достойное) Поэтому не хочу придираться)

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/usecase/interfaces.go
> +		saveStorage()
приватные методы же не доступны в других пакетах

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/usecase/devops.go
> +		<-uc.C
если у тебя uc.writeToFileWithDuration == false , а uc.synchWriteFile == true , то тикеру неоткуда взять и здесь горутина будет просто висеть.

2022-06-22 18:37 UTC, sergeysergeevru commented on internal/usecase/devops.go
> +		<-uc.C
и синхронной записи не получится. Синхронная запись - это когда пришел реквест на апдейт метрики, мы сходили в репозитори, он сохранил все в файл, а потом мы ответили пользователю, что все гуд (или не гуд если записать не смогли)

2022-06-24 13:20 UTC, Konab commented on internal/app/server/router.go
> +		)
да, без него я не прохожу тест на возврат 501 ошибки если не поддерживается какой-то тип метрики
не понимаю как по другому сделать(

2022-06-24 14:21 UTC, Konab commented on internal/app/server/router.go
> +			w.Header().Set("Content-Type", "text/html")
тогда тесты не проходят
```Error:      	"text/plain" does not contain "text/html"```

2022-06-24 19:31 UTC, sergeysergeevru approved these changes
Получилось хорошо) Спасибо за хорошо читаемый код!

2022-06-24 19:31 UTC, sergeysergeevru commented on cmd/agent/main.go
> +	agent_config "devops-tpl/config/agent"
не прям большая проблема, но camel case предпочтительней в комьюнити)

2022-06-24 19:31 UTC, sergeysergeevru commented on internal/app/server/router.go
> +		r.Post("/{metricType}/{metricName}/{metricValue}", notImplemented())
тут придерусь к названиям переменных, когда смотришь такой кусок кода, вообще не понятно что стоит за uc и l. Под uc могу догадаться что usercase. Но все равно не очевидно. В общем давай давать названия переменным, чтобы код был самодокументируемым) 
<img width="750" alt="Screenshot 2022-06-24 at 11 14 08 PM" src="https://user-images.githubusercontent.com/12248824/175650293-7c1c6bfd-2995-4352-ae22-5277812ddeec.png">

2022-06-24 19:31 UTC, sergeysergeevru commented on internal/app/server/router.go
> +		names, err := uc.GetMetricNames(context.TODO())
не помню уже тебе я писал или нет про выбор между контекстом из реквеста или TODO) С моей точки зрения лучше взять `r.Context()` допустим в каком-нибудь middleware мы можем поставить timeout на реквест (допустим мы по контракту должны рвать запрос) и тогда мы можем передать этот котекст с таймаутом в репу)

2022-06-24 19:31 UTC, sergeysergeevru commented on internal/infrastructure/repo/metric.go
> +		metricRepo.UploadFromFile(context.TODO())
да, а тут todo вполне норм)

2022-06-24 19:31 UTC, sergeysergeevru commented on internal/usecase/devops.go
> +	}
вроде этот кусок нам не нужен больше. Мы же по тикеру кидаем данные в канал)

2022-06-30 14:35 UTC, merged